on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  git-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - env:
          release-name: sphinx-uedoc-demo-${{ github.event.release.tag_name }}.zip
      - uses: actions/setup-python@v2
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Wheels
        run: |
          python -m pip install -r requirements.txt
          python -m pip install --user --upgrade setuptools wheel
          python setup.py sdist bdist_wheel

      - name: Package Wheels
        run: |
          zip -r $release-name dist/*

      - name: Deploy Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: success()
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: $release-name