---
name: "Pypi deploy"

on: push 

jobs:
  pre-release:
    name: "Pypi deploy"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2
      - name: "Set release name"
        run: |
          export RELEASE_NAME="${{ github.event.repository.name }}-dev"
          echo "::set-env name=NAME::$RELEASE_NAME"
        
      - name: "Install Requirements"
        if: success()
        run: |
            python -m pip install -r requirements.txt
            python -m pip install wheel

      - name: "Build Package"
        if: success()
        run: |
            cd $GITHUB_WORKSPACE
            python setup.py sdist bdist_wheel
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: pypi-AgENdGVzdC5weXBpLm9yZwIkMzYzMjY4YTItMWU0Ny00NTA5LWJhM2UtYTU4MDgwN2I5ZTkxAAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiCSzyVFCmWtt0kHWQ2l960uykC5FqVX9lj-Did0PDu27w
          repository_url: https://test.pypi.org/legacy/
